from flask import Flask, request, render_template, send_file
from markupsafe import escape
import pickle
import os
from datetime import datetime


vector = pickle.load(open("vectorizer.pk", 'rb'))
model = pickle.load(open("finalized_model.pk", 'rb'))


app = Flask(__name__)

@app.route('/')
def home():
    return render_template("index.html")

@app.route('/prediction', methods=['GET', 'POST'])
def prediction():
    if request.method == "POST":
        news = str(request.form['news'])
        print(news)


        predict = model.predict(vector.transform([news]))[0]
        print(predict)

        return render_template("prediction.html", prediction_text = "News headline is -> {}".format(predict))



    else:
        return render_template("prediction.html")

@app.route('/generate_report', methods=['POST'])
def generate_report():
    try:
        news = str(request.form['news'])
        prediction = model.predict(vector.transform([news]))[0]

        # Create HTML content for PDF
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Fake News Detection Report</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; }}
                .header {{ text-align: center; color: #333; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }}
                .result {{ font-size: 24px; font-weight: bold; text-align: center; margin: 30px 0; }}
                .real {{ color: #28a745; }}
                .fake {{ color: #dc3545; }}
                .details {{ margin: 20px 0; }}
                .footer {{ text-align: center; margin-top: 50px; font-size: 12px; color: #666; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>Fake News Detection Report</h1>
                <p>Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            </div>

            <div class="details">
                <h2>Analysis Details</h2>
                <p><strong>Input Headline:</strong> {escape(news)}</p>
                <p><strong>Prediction:</strong> <span class="result {'real' if prediction == 'REAL' else 'fake'}">{prediction}</span></p>
                <p><strong>Confidence:</strong> High (AI-Powered Analysis)</p>
            </div>

            <div class="footer">
                <p>Report generated by Fake News Detector</p>
                <p>Created by aps4934 | https://github.com/aps4934/Fake-News-Detection</p>
            </div>
        </body>
        </html>
        """

        # Generate PDF filename
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        pdf_filename = f"fake_news_report_{timestamp}.pdf"

        # Generate PDF using WeasyPrint
        from weasyprint import HTML, CSS
        HTML(string=html_content).write_pdf(pdf_filename)

        # Return PDF file
        return send_file(pdf_filename, as_attachment=True, download_name=pdf_filename)

    except Exception as e:
        print(f"Error generating PDF: {e}")
        return "Error generating report", 500

@app.route('/health')
def health():
    return {"status": "healthy", "timestamp": datetime.now().isoformat()}

if __name__ == '__main__':
    app.run()
